---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  product_name: chef
  enforce_idempotency: true
  multiple_converge: 2
  solo_rb:
    treat_deprecation_warnings_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux-2
    driver_config:
      box: ywatase/amzn2
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: opensuse-leap-15
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: client_5.6
    attributes:
      percona:
        apt:
          keyserver: hkp://pgp.mit.edu:80
        version: "5.6"
    run_list:
      - recipe[percona::client]
      - recipe[percona::toolkit]
  - name: client_5.7
    attributes:
      percona:
        apt:
          keyserver: hkp://pgp.mit.edu:80
        version: "5.7"
    run_list:
      - recipe[percona::client]
      - recipe[percona::toolkit]

  - name: server_5.6
    attributes:
      percona:
        apt:
          keyserver: hkp://pgp.mit.edu:80
        version: "5.6"
        server:
          datadir: /tmp/mysql
          debian_password: d3b1an
          jemalloc: true
          root_password: r00t
    run_list:
      - recipe[percona::server]
      - recipe[percona::backup]

  - name: server_5.7
    attributes:
      percona:
        apt:
          keyserver: hkp://pgp.mit.edu:80
        version: "5.7"
        server:
          datadir: /tmp/mysql
          debian_password: d3b1an
          jemalloc: true
          root_password: r00t
    run_list:
      - recipe[percona::server]
      - recipe[percona::backup]
